### ISSUE TITLE
Support keytabs with multiple principals i.e. GSS_C_NO_CREDENTIAL

### ISSUE THREAD

**Issue by simmel** [COUR4G3/flask-gssapi#6]
Heyo!

We're using flask-gssapi with an app where the front and forward DNS isn't the same and depending on the clients Kerberos implementation the client would ask for the principal based on the forward or the reverse DNS name.

I.e:
```
$ host the-service.it.su.se
the-service.it.su.se has address 127.0.0.1
$ host 127.0.0.1
1.0.0.127.in-addr.arpa domain name pointer the-server-name01.it.su.se.
$
```

This can either be solved by setting the reverse and forward DNS to the same name, in this case not possible, or having both principals in the keytab and configuring the GSSAPI lib to pick which ever the client wants by setting the credential to `GSS_C_NO_CREDENTIAL` (which is NULL or None), see https://web.mit.edu/kerberos/krb5-1.13/doc/appdev/gssapi.html#acceptor-names

[flask_gssapi.py]#L40-L42(https://github.com/COUR4G3/flask-gssapi/blob/d3842e14/flask_gssapi.py#L40-L42) is:
```python
        app.extensions['gssapi'] = {
            'creds': gssapi.Credentials(name=name, usage='accept'),
        }

```

and if we change it to:
```python
        app.extensions['gssapi'] = {
            'creds': gssapi.Credentials(name=None, usage='accept'),
        }

```

it uses `GSS_C_NO_CREDENTIAL`.

Sure we can put the above code in our app.py but maybe we can change #L36-37 to:
```python
        name = app.config.get('GSSAPI_HOSTNAME', None)
        if name is not None:
            principal = '{}@{}'.format(service_name, hostname)
            name = gssapi.Name(principal, gssapi.NameType.hostbased_service)
```

I'm well aware that this is a breaking change but I don't see how we can introduce the change without adding unnecessary complexion (like adding another environment variables).

We're willing to contribute this very small change. This is just the issue to discuss it.

**Comment by COUR4G3** [comment]
Wouldn't this work:

```python
        name = app.config.get('GSSAPI_HOSTNAME', socket.getfqdn())
        if name is not None:
            principal = '{}@{}'.format(service_name, hostname)
            name = gssapi.Name(principal, gssapi.NameType.hostbased_service)

```

This would still allow the default behaviour, but when you explicitly set `GSSAPI_HOSTNAME` to `None` in config it will use `GSS_C_NO_CREDENTIAL`.

**Comment by simmel** [comment]
I thought `GSSAPI_HOSTNAME` could also be configured via an environment variable which confused me (since `os.env.get()` returns `None` if the variable doesn't exist and empty string if it's set to nothing).

Please also make a release after you accept our PR so we can just depend on the new version and not maintain a local fork of it.  Thanks!

**Comment by COUR4G3** [comment]
Busy preparing a release now.

**Comment by COUR4G3** [comment]
And release is done. 1.4.0 should be available on PyPi.

**Comment by simmel** [comment]
It is, thank you for the very fast merge and release!
