### ISSUE TITLE
require_auth decorator seems to need parentheses upon being called

### ISSUE THREAD

**Issue by prppedro** [COUR4G3/flask-gssapi#9]
According to README file, calling the decorator is just a question of doing as follows: 

```
@app.route('/secret')
@gssapi.require_auth
def secret_view():
```

However, this causes the following error: 

> TypeError: require_auth() takes 1 positional argument but 2 were given

Calling the decorator as follows seems to solve the problem: 
`@gssapi.require_auth()`

My environment is as follows: 
Python 3.7.3
Flask 1.1.2
Werkzeug 1.0.1
Debian Buster

Thanks, 
Att.,
-trp

**Comment by COUR4G3** [comment]
I think I know why this happens. I must just do some testing my side and will push a fix.

**Comment by COUR4G3** [comment]
Apparently I forgot how to Python when I wrote the documentation, have updated it to reflect the correct syntax with the parentheses.
